#!/bin/bash
sbatch lhs_cc_0.slurm
sbatch lhs_cc_1.slurm
sbatch lhs_cc_2.slurm
sbatch lhs_cc_3.slurm
sbatch lhs_cc_4.slurm
sbatch lhs_cc_5.slurm
sbatch lhs_cc_6.slurm
sbatch lhs_cc_7.slurm
sbatch lhs_cc_8.slurm
sbatch lhs_cc_9.slurm
sbatch lhs_cc_10.slurm
sbatch lhs_cc_11.slurm
sbatch lhs_cc_12.slurm
sbatch lhs_cc_13.slurm
sbatch lhs_cc_14.slurm
sbatch lhs_cc_15.slurm
sbatch lhs_cc_16.slurm
sbatch lhs_cc_17.slurm
sbatch lhs_cc_18.slurm
sbatch lhs_cc_19.slurm
sbatch lhs_cc_20.slurm
sbatch lhs_cc_21.slurm
sbatch lhs_cc_22.slurm
sbatch lhs_cc_23.slurm
sbatch lhs_cc_24.slurm
sbatch lhs_cc_25.slurm
sbatch lhs_cc_26.slurm
sbatch lhs_cc_27.slurm
sbatch lhs_cc_28.slurm
sbatch lhs_cc_29.slurm
sbatch lhs_cc_30.slurm
sbatch lhs_cc_31.slurm
