#!/bin/bash
sbatch lhs_cc_0.slurm
sbatch lhs_cc_1.slurm
sbatch lhs_cc_2.slurm
sbatch lhs_cc_3.slurm
sbatch lhs_cc_4.slurm
sbatch lhs_cc_5.slurm
sbatch lhs_cc_6.slurm
sbatch lhs_cc_7.slurm
sbatch lhs_cc_8.slurm
sbatch lhs_cc_9.slurm
sbatch lhs_cc_10.slurm
sbatch lhs_cc_11.slurm
sbatch lhs_cc_12.slurm
sbatch lhs_cc_13.slurm
sbatch lhs_cc_14.slurm
sbatch lhs_cc_15.slurm
sbatch lhs_cc_16.slurm
sbatch lhs_cc_17.slurm
sbatch lhs_cc_18.slurm
sbatch lhs_cc_19.slurm
sbatch lhs_cc_20.slurm
sbatch lhs_cc_21.slurm
sbatch lhs_cc_22.slurm
sbatch lhs_cc_23.slurm
sbatch lhs_cc_24.slurm
sbatch lhs_cc_25.slurm
sbatch lhs_cc_26.slurm
sbatch lhs_cc_27.slurm
sbatch lhs_cc_28.slurm
sbatch lhs_cc_29.slurm
sbatch lhs_cc_30.slurm
sbatch lhs_cc_31.slurm
sbatch lhs_cc_32.slurm
sbatch lhs_cc_33.slurm
sbatch lhs_cc_34.slurm
sbatch lhs_cc_35.slurm
sbatch lhs_cc_36.slurm
sbatch lhs_cc_37.slurm
sbatch lhs_cc_38.slurm
sbatch lhs_cc_39.slurm
sbatch lhs_cc_40.slurm
sbatch lhs_cc_41.slurm
sbatch lhs_cc_42.slurm
sbatch lhs_cc_43.slurm
sbatch lhs_cc_44.slurm
sbatch lhs_cc_45.slurm
sbatch lhs_cc_46.slurm
sbatch lhs_cc_47.slurm
sbatch lhs_cc_48.slurm
sbatch lhs_cc_49.slurm
sbatch lhs_cc_50.slurm
sbatch lhs_cc_51.slurm
sbatch lhs_cc_52.slurm
sbatch lhs_cc_53.slurm
sbatch lhs_cc_54.slurm
sbatch lhs_cc_55.slurm
sbatch lhs_cc_56.slurm
sbatch lhs_cc_57.slurm
sbatch lhs_cc_58.slurm
sbatch lhs_cc_59.slurm
sbatch lhs_cc_60.slurm
sbatch lhs_cc_61.slurm
sbatch lhs_cc_62.slurm
sbatch lhs_cc_63.slurm
sbatch lhs_cc_64.slurm
sbatch lhs_cc_65.slurm
sbatch lhs_cc_66.slurm
sbatch lhs_cc_67.slurm
sbatch lhs_cc_68.slurm
sbatch lhs_cc_69.slurm
sbatch lhs_cc_70.slurm
sbatch lhs_cc_71.slurm
sbatch lhs_cc_72.slurm
sbatch lhs_cc_73.slurm
sbatch lhs_cc_74.slurm
sbatch lhs_cc_75.slurm
sbatch lhs_cc_76.slurm
sbatch lhs_cc_77.slurm
sbatch lhs_cc_78.slurm
sbatch lhs_cc_79.slurm
sbatch lhs_cc_80.slurm
sbatch lhs_cc_81.slurm
sbatch lhs_cc_82.slurm
sbatch lhs_cc_83.slurm
sbatch lhs_cc_84.slurm
sbatch lhs_cc_85.slurm
sbatch lhs_cc_86.slurm
sbatch lhs_cc_87.slurm
sbatch lhs_cc_88.slurm
sbatch lhs_cc_89.slurm
sbatch lhs_cc_90.slurm
sbatch lhs_cc_91.slurm
sbatch lhs_cc_92.slurm
sbatch lhs_cc_93.slurm
sbatch lhs_cc_94.slurm
sbatch lhs_cc_95.slurm
sbatch lhs_cc_96.slurm
sbatch lhs_cc_97.slurm
sbatch lhs_cc_98.slurm
sbatch lhs_cc_99.slurm
